version: '3'
services:
  jackrabbit:
    image: node
    working_dir: /code
    volumes:
      - .:/code
    depends_on:
      - rabbit
    environment:
      RABBIT_URL: 'amqp://rabbit'
  rabbit:
    image: rabbitmq
